# Pandas时间序列与日期

## 时间构造函数

In [1]:
import datetime
import pandas as pd
import numpy as np

### pandas构造时间的函数
pandas与datetime() 与 python的datetime模块一致

In [2]:
now = datetime.datetime.now()

In [3]:
type(now)

datetime.datetime

In [4]:
now1 = pd.datetime.now()

In [5]:
type(now1)

datetime.datetime

In [6]:
now.date()

datetime.date(2022, 2, 16)

In [7]:
now.time()

datetime.time(11, 52, 30, 41670)

In [8]:
now.hour, now.day, now.year, now.month, now.second

(11, 16, 2022, 2, 30)

In [9]:
now.strftime('%Y-%m/%d')

'2022-02/16'

### 时间戳pd.Timestamp 和 时间段pd.Period

时间戳是最基本的时间序列数据，用于把数值与时点关联在一起。Pandas 对象通过时间戳调用时点数据。

In [18]:
ts = pd.Timestamp('2022-01-01 11:13:19', freq='H')

In [19]:
ts

Timestamp('2022-01-01 11:13:19', freq='H')

In [20]:
ts + 1

C:\Users\Dancer\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Addition/subtraction of integers and integer-arrays to Timestamp is deprecated, will be removed in a future version.  Instead of adding/subtracting `n`, use `n * self.freq`
  """Entry point for launching an IPython kernel.

Timestamp('2022-01-01 12:13:19', freq='H')

In [24]:
ts1 = pd.Period('2011-01-01 11:13:19', freq='D')
ts1

Period('2011-01-01', 'D')

In [25]:
ts1 + 1

Period('2011-01-02', 'D')

freq参数的可选字符串

|别名|  偏移量类型|  说明|
|-|-|
|D  |  Day |  每日历日|
|B   | BusinessDay|   每工作日|
|H   | Hour   |每小时|
|T或min |  Minute  | 每分|
|S   |Second  |  每秒 |
|L或ms |  Milli |  每毫秒（即每千分之一秒）|
|U   | Micro   | 每微秒（即每百万分之一秒）|
|M   | MonthEnd   | 每月最后一个日历日|
|BM   | BusinessMonthEnd |   每月最后一个工作日|
|MS    |MonthBegin   | 每月第一个日历日|
|BMS   | BusinessMonthBegin  | 每月第一个工作日

不过，大多数情况下，用时间段改变变量更自然。Period 表示的时间段更直观，还可以用日期时间格式的字符串进行推断。

时间戳和时间段都可以与整数做加减运算，以freq指定的参数为单位

Timestamp 与 Period 可以用作索引。作为索引的 Timestamp 与 Period 列表则被强制转换为对应的 DatetimeIndex 与 PeriodIndex。

In [27]:
date = [pd.Timestamp('2015-05-01'), pd.Timestamp('2012-05-02'), pd.Timestamp('2012-05-03')]
ts = pd.Series(np.random.randn(3), index=date)
ts

2015-05-01    0.388782
2012-05-02   -0.994027
2012-05-03    1.043194
dtype: float64

In [28]:
ts.index

DatetimeIndex(['2015-05-01', '2012-05-02', '2012-05-03'], dtype='datetime64[ns]', freq=None)

In [29]:
date1 = [pd.Period('2015-05-01'), pd.Period('2012-05-02'), pd.Period('2012-05-03')]
ts1 = pd.Series(np.random.randn(3), index=date1)
ts1

2015-05-01    1.616632
2012-05-02   -1.601359
2012-05-03   -1.353825
Freq: D, dtype: float64

In [30]:
ts1.index

PeriodIndex(['2015-05-01', '2012-05-02', '2012-05-03'], dtype='period[D]', freq='D')

### 构造时间序列date_range\bdate_range() 


- 实际工作中，经常要生成含大量时间戳的超长索引，一个个输入时间戳又枯燥，又低效
- 如果时间戳是定频的，用date_range()与bdate_range()函数即可创DatetimeIndex。
- date_range 默认的频率是日历日，bdate_range 的默认频率是工作日

In [60]:
pd.date_range(start='2008-01-01', end='2020-01-01', freq='2Y', name='时间')

DatetimeIndex(['2008-12-31', '2010-12-31', '2012-12-31', '2014-12-31',
               '2016-12-31', '2018-12-31'],
              dtype='datetime64[ns]', name='时间', freq='2A-DEC')

In [62]:
pd.bdate_range(start='2022-02-01', end='2022-02-16', freq='2B')

DatetimeIndex(['2022-02-01', '2022-02-03', '2022-02-07', '2022-02-09',
               '2022-02-11', '2022-02-15'],
              dtype='datetime64[ns]', freq='2B')

In [70]:
# periods 指定时间序列的数据个数，注意不要再指定end结束时间，否则可能会产生冲突
pd.bdate_range(start='2022-02-16' ,periods=5, freq='2B')

DatetimeIndex(['2022-02-16', '2022-02-18', '2022-02-22', '2022-02-24',
               '2022-02-28'],
              dtype='datetime64[ns]', freq='2B')

## 转换时间戳

### to_datetime()

to_datetime 函数用于转换字符串、纪元式及混合的日期 Series 或日期列表。

In [76]:
df = pd.DataFrame(pd.Series(data=['2005/11/23', 
                  '2010.12.31', 
                  'Jul, 31, 2009', 
                  '2010-01-10', 
                  'Aug-24-2019', 
                  'Feb 1 2020',
                  '01-14-2012',
                  None], name='时间'))

In [78]:
df['value'] = np.random.randint(0, 100, size=8)
df

              时间  value
0     2005/11/23     24
1     2010.12.31     12
2  Jul, 31, 2009     15
3     2010-01-10     55
4    Aug-24-2019     67
5     Feb 1 2020      5
6     01-14-2012     59
7           None     74

In [79]:
df.sort_values('时间')

              时间  value
6     01-14-2012     59
0     2005/11/23     24
3     2010-01-10     55
1     2010.12.31     12
4    Aug-24-2019     67
5     Feb 1 2020      5
2  Jul, 31, 2009     15
7           None     74

In [83]:
# 强制类型转换解决一个数据的临时转换
int('123')

123

In [88]:
# 数据的批量转换和单个转换是不同的操作

np.array([1,2,3]).astype(np.float64)

array([1., 2., 3.])

转换的是 Series时，返回的是具有相同的索引的Series，日期时间列表则会被转换为DatetimeIndex

pd.to_datetime(pd.Series(['2005/11/23', 
                  '2010.12.31', 
                  'Jul, 31, 2009', 
                  '2010-01-10', 
                  'Aug-24-2019', 
                  'Feb 1 2020',
                  '01-14-2012',
                  None]))

In [95]:
type(pd.datetime.now())

datetime.datetime

In [96]:
df['时间'].astype(datetime.datetime)

TypeError: dtype '<class 'datetime.datetime'>' not understood

In [97]:
# 时间类型的字符串，可以直接用to_datetime函数转换程Timestamp类型
# 并且，空值会自动被解析成NaT，时间空值
# NaN not a number
# NaT not a time
pd.to_datetime(df['时间'])

0   2005-11-23
1   2010-12-31
2   2009-07-31
3   2010-01-10
4   2019-08-24
5   2020-02-01
6   2012-01-14
7          NaT
Name: 时间, dtype: datetime64[ns]

In [98]:
pd.to_datetime('2022-01-01')

Timestamp('2022-01-01 00:00:00')

In [99]:
df['时间'] = pd.to_datetime(df['时间'])

In [101]:
df.sort_values('时间')

          时间  value
0 2005-11-23     24
2 2009-07-31     15
3 2010-01-10     55
1 2010-12-31     12
6 2012-01-14     59
4 2019-08-24     67
5 2020-02-01      5
7        NaT     74

解析欧式日期（日-月-年），要用 dayfirst 关键字参数：

In [103]:
pd.to_datetime(['04-01-2012 10:00'], dayfirst=True)

DatetimeIndex(['2012-01-04 10:00:00'], dtype='datetime64[ns]', freq=None)

dayfirst 并没有那么严苛，如果不能把第一个数解析为日，就会以 dayfirst 为 False 进行解析。

In [104]:
pd.to_datetime(['2012-01-12', '01-14-2012'], dayfirst=True)

DatetimeIndex(['2012-01-12', '2012-01-14'], dtype='datetime64[ns]', freq=None)

to_datetime 转换单个字符串时，返回的是单个 Timestamp。

In [105]:
pd.to_datetime('2022-01-02')

Timestamp('2022-01-02 00:00:00')

Timestamp 仅支持字符串输入，不支持 dayfirst、format 等字符串解析选项，如果要使用这些选项，就要用 to_datetime

In [ ]:
pd.Timestamp('2012-01-01')

In [108]:
pd.Timestamp('2012年12月10日')

ValueError: could not convert string to Timestamp

In [112]:
pd.to_datetime('2012年12月10日', format='%Y年%m月%d日')

Timestamp('2012-12-10 00:00:00')

### DatetimeIndex构造

Pandas 还支持直接使用 DatetimeIndex 构建时间序列：

In [113]:
pd.DatetimeIndex(['2018-01-01', '2018-01-3', '2018-01-05'])

DatetimeIndex(['2018-01-01', '2018-01-03', '2018-01-05'], dtype='datetime64[ns]', freq=None)

创建 DatetimeIndex 时，freq='infer' 可自动推断索引的频率

In [115]:
time_indexes = pd.DatetimeIndex(['2018-01-01', '2018-01-3', '2018-01-05'], freq='infer')

In [117]:
time_indexes[0] + 1

C:\Users\Dancer\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Addition/subtraction of integers and integer-arrays to Timestamp is deprecated, will be removed in a future version.  Instead of adding/subtracting `n`, use `n * self.freq`
  """Entry point for launching an IPython kernel.

Timestamp('2018-01-03 00:00:00', freq='2D')

### 提供格式参数format

要实现精准转换，除了传递 datetime 字符串，还可以通过format参数来指定格式，指定此参数还可以加速转换速度。

Y  年
m  月
d  日
H  时
M  分
S  秒

In [ ]:
2011年11月12日



2011-12月5号

### 无效数据

不可解析时，默认值 errors='raise' 会触发错误：

In [119]:
# 有错就要处理，默认值就Ok
pd.to_datetime(['2009/07/30', 'asd'], errors='raise')

ParserError: Unknown string format: asd

errors='ignore' 返回原始输入：

In [122]:
indexes = pd.to_datetime(['2009-07-30', 'asd'], errors='ignore')

In [123]:
indexes[0]

'2009-07-30'

errors='coerce' 把无法解析的数据转换为 NaT，即不是时间（Not a Time）：

In [126]:
indexes = pd.to_datetime(['2009-07-30', 'asd'], errors='coerce')

In [127]:
indexes[0]

Timestamp('2009-07-30 00:00:00')

In [129]:
pd.to_datetime('2012年12月11日', errors='ignore')

'2012年12月11日'

In [133]:
def my_transform(x):
    if x == None:
        return None
    
    # 解决'2012年12月11日'类问题
    if x.endswith('日'):
        return pd.to_datetime(x, format='%Y年%m月%d日')
    
    # 解决'2012-01-01', 'asd'两类
    obj = pd.to_datetime(x, errors='ignore')
    
    if isinstance(obj, str):
        return np.nan
    else:
        return obj

In [134]:
pd.Series(data=['2012-01-01', 'asd', '2012年12月11日', '2003-02-03', None]).map(my_transform)

0   2012-01-01
1          NaT
2   2012-12-11
3   2003-02-03
4          NaT
dtype: datetime64[ns]

## 索引访问

### 常规索引访问
DatetimeIndex 可以当作常规索引，支持选择、切片等方法。

In [135]:
rng = pd.date_range(start='2022-1-1', periods=20, freq='M')
rng

DatetimeIndex(['2022-01-31', '2022-02-28', '2022-03-31', '2022-04-30',
               '2022-05-31', '2022-06-30', '2022-07-31', '2022-08-31',
               '2022-09-30', '2022-10-31', '2022-11-30', '2022-12-31',
               '2023-01-31', '2023-02-28', '2023-03-31', '2023-04-30',
               '2023-05-31', '2023-06-30', '2023-07-31', '2023-08-31'],
              dtype='datetime64[ns]', freq='M')

In [136]:
ts = pd.Series(data=np.random.randn(len(rng)), index=rng)

In [137]:
ts

2022-01-31    0.021027
2022-02-28   -0.053045
2022-03-31    1.332245
2022-04-30    0.999394
2022-05-31    0.477203
2022-06-30   -0.515224
2022-07-31   -0.134608
2022-08-31   -0.801372
2022-09-30    0.510634
2022-10-31    0.513671
2022-11-30   -1.721545
2022-12-31    1.046892
2023-01-31    1.202192
2023-02-28   -0.775141
2023-03-31    1.568975
2023-04-30    0.771119
2023-05-31    0.168035
2023-06-30    0.055963
2023-07-31   -2.380672
2023-08-31    0.613003
Freq: M, dtype: float64

In [138]:
ts.index

DatetimeIndex(['2022-01-31', '2022-02-28', '2022-03-31', '2022-04-30',
               '2022-05-31', '2022-06-30', '2022-07-31', '2022-08-31',
               '2022-09-30', '2022-10-31', '2022-11-30', '2022-12-31',
               '2023-01-31', '2023-02-28', '2023-03-31', '2023-04-30',
               '2023-05-31', '2023-06-30', '2023-07-31', '2023-08-31'],
              dtype='datetime64[ns]', freq='M')

In [140]:
ts.index[0]

Timestamp('2022-01-31 00:00:00', freq='M')

In [141]:
ts.index[-1]

Timestamp('2023-08-31 00:00:00', freq='M')

In [142]:
ts.index[:5]

DatetimeIndex(['2022-01-31', '2022-02-28', '2022-03-31', '2022-04-30',
               '2022-05-31'],
              dtype='datetime64[ns]', freq='M')

### 局部字符串索引
能解析为时间戳的日期与字符串可以作为索引的参数：

pandas 为访问较长的时间序列提供了便捷方法，年、年月字符串均可：

带 DatetimeIndex 的 DateFrame 也支持这种切片方式。局部字符串是标签切片的一种形式，这种切片也包含截止时点，即，与日期匹配的时间也会包含在内：

In [ ]:
DatetimeIndex

In [145]:
ts.index

DatetimeIndex(['2022-01-31', '2022-02-28', '2022-03-31', '2022-04-30',
               '2022-05-31', '2022-06-30', '2022-07-31', '2022-08-31',
               '2022-09-30', '2022-10-31', '2022-11-30', '2022-12-31',
               '2023-01-31', '2023-02-28', '2023-03-31', '2023-04-30',
               '2023-05-31', '2023-06-30', '2023-07-31', '2023-08-31'],
              dtype='datetime64[ns]', freq='M')

In [143]:
# DatetimeIndex 作为索引
ts['2022']

2022-01-31    0.021027
2022-02-28   -0.053045
2022-03-31    1.332245
2022-04-30    0.999394
2022-05-31    0.477203
2022-06-30   -0.515224
2022-07-31   -0.134608
2022-08-31   -0.801372
2022-09-30    0.510634
2022-10-31    0.513671
2022-11-30   -1.721545
2022-12-31    1.046892
Freq: M, dtype: float64

In [146]:
ts['2022-3']

2022-03-31    1.332245
Freq: M, dtype: float64

In [148]:
ts['2022.1.31']

0.021026767286337178

In [150]:
ts['2022-1':'2022-5']

2022-01-31    0.021027
2022-02-28   -0.053045
2022-03-31    1.332245
2022-04-30    0.999394
2022-05-31    0.477203
Freq: M, dtype: float64

In [152]:
AAPL = pd.read_csv('AAPL.csv')

In [157]:
AAPL.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9296 entries, 0 to 9295
Data columns (total 7 columns):
Date         9296 non-null datetime64[ns]
Open         9296 non-null float64
High         9296 non-null float64
Low          9296 non-null float64
Close        9296 non-null float64
Adj Close    9296 non-null float64
Volume       9296 non-null int64
dtypes: datetime64[ns](1), float64(5), int64(1)
memory usage: 508.5 KB

In [154]:
AAPL.head()

         Date      Open      High       Low     Close  Adj Close     Volume
0  1980-12-12  0.513393  0.515625  0.513393  0.513393   0.421597  117258400
1  1980-12-15  0.488839  0.488839  0.486607  0.486607   0.399601   43971200
2  1980-12-16  0.453125  0.453125  0.450893  0.450893   0.370272   26432000
3  1980-12-17  0.462054  0.464286  0.462054  0.462054   0.379437   21610400
4  1980-12-18  0.475446  0.477679  0.475446  0.475446   0.390436   18362400

In [156]:
AAPL['Date'] = pd.to_datetime(AAPL['Date'])

In [161]:
AAPL.set_index('Date')['2017-10']

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2017-10-02,154.259995,154.449997,152.720001,153.809998,153.809998,18698800
2017-10-03,154.009995,155.089996,153.910004,154.479996,154.479996,16230300
2017-10-04,153.630005,153.860001,152.460007,153.479996,153.479996,20163800
2017-10-05,154.179993,155.440002,154.050003,155.389999,155.389999,21283800
2017-10-06,154.970001,155.490005,154.559998,155.300003,155.300003,17407600
2017-10-09,155.809998,156.729996,155.490005,155.839996,155.839996,16262900
2017-10-10,156.059998,158.000000,155.100006,155.899994,155.899994,15617000
2017-10-11,155.970001,156.979996,155.750000,156.550003,156.550003,16905600
2017-10-12,156.350006,157.369995,155.729996,156.000000,156.000000,16125100
2017-10-13,156.729996,157.279999,156.410004,156.990005,156.990005,16394200
2017-10-16,157.899994,160.000000,157.649994,159.880005,159.880005,24121500
2017-10-17,159.779999,160.869995,159.229996,160.470001,160.470001,18997300
2017-10-18,160.419998,160.710007,159.600006,159.759995,159.759995,16374200
2017-10-19,156.750000,157.080002,155.020004,155.979996,155.979996,42584200
2017-10-20,156.610001,157.750000,155.960007,156.250000,156.250000,23974100
2017-10-23,156.889999,157.690002,155.500000,156.169998,156.169998,21867200

## 日期/时间属性
以下日期/时间属性可以访问 Timestamp 或 DatetimeIndex对象。

In [ ]:
datetime

|属性|说明|
|-|-|
|year	|datetime 的年|
|month	|datetime 的月|
|day	|datetime 的日|
|hour	|datetime 的小时|
|minute	|datetime 的分钟|
|second	|datetime 的秒|
|microsecond	|datetime 的微秒|
|nanosecond	|datetime 的纳秒|
|date	|返回 datetime.date（不包含时区信息）|
|time	|返回 datetime.time（不包含时区信息）|
|timetz	|返回带本地时区信息的 datetime.time|
|dayofyear	|一年里的第几天|
|weekofyear	|一年里的第几周|
|week	|一年里的第几周|
|dayofweek	|一周里的第几天，Monday=0, Sunday=6|
|weekday	|一周里的第几天，Monday=0, Sunday=6|
|weekday_name	|这一天是星期几 （如，Friday）|
|quarter	|日期所处的季节：Jan-Mar = 1，Apr-Jun = 2 等|
|days_in_month	|日期所在的月有多少天|
|is_month_start	|逻辑判断是不是月初（由频率定义）|
|is_month_end	|逻辑判断是不是月末（由频率定义）|
|is_quarter_start	|逻辑判断是不是季初（由频率定义）|
|is_quarter_end	|逻辑判断是不是季末（由频率定义）|
|is_year_start	|逻辑判断是不是年初（由频率定义）|
|is_year_end	|逻辑判断是不是年末（由频率定义）|
|is_leap_year	|逻辑判断是不是日期所在年是不是闰年|

In [ ]:
# Timestimpe  DatetimeIndex

In [176]:
ts2 = pd.Timestamp('2022-01-22 11:10:9')
ts2.year, ts2.month, ts2.day, ts2.hour, ts2.minute, ts2.second

(2022, 1, 22, 11, 10, 9)

In [177]:
ts1 = pd.DatetimeIndex(data=pd.date_range('2022-01-01', periods=10, freq='M'))
ts1

DatetimeIndex(['2022-01-31', '2022-02-28', '2022-03-31', '2022-04-30',
               '2022-05-31', '2022-06-30', '2022-07-31', '2022-08-31',
               '2022-09-30', '2022-10-31'],
              dtype='datetime64[ns]', freq='M')

In [179]:
ts1.month

Int64Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')

In [181]:
ts1.is_month_start

array([False, False, False, False, False, False, False, False, False,
       False])

In [182]:
ts1.is_year_start

array([False, False, False, False, False, False, False, False, False,
       False])

## pandas对象的dt属性

Series对象和DataFrame的列数据提供了dt属性接口（accessors），对应日期时间数据，通过这个接口可以快速实现特定的功能，非常快捷。

In [194]:
AAPL['Date'].dt.is_month_start

0       False
1       False
2       False
3       False
4       False
        ...
9291    False
9292    False
9293    False
9294    False
9295    False
Name: Date, Length: 9296, dtype: bool

## 重采样

Pandas 有一个虽然简单，但却强大、高效的功能，可在频率转换时执行重采样，如，将秒数据转换为 5 分钟数据，这种操作在金融等领域里的应用非常广泛。

resample() 是基于时间的分组操作，每个组都遵循归纳方法。

从 0.18.0 版开始，resample() 可以直接用于 DataFrameGroupBy 对象，

注意：重采样一定要以时间类型做Index

In [ ]:
DatetimeIndex

In [198]:
AAPL['year'] = AAPL['Date'].dt.year

In [199]:
AAPL.head()

,Date,Open,High,Low,Close,Adj Close,Volume,year
0,1980-12-12,0.513393,0.515625,0.513393,0.513393,0.421597,117258400,1980
1,1980-12-15,0.488839,0.488839,0.486607,0.486607,0.399601,43971200,1980
2,1980-12-16,0.453125,0.453125,0.450893,0.450893,0.370272,26432000,1980
3,1980-12-17,0.462054,0.464286,0.462054,0.462054,0.379437,21610400,1980
4,1980-12-18,0.475446,0.477679,0.475446,0.475446,0.390436,18362400,1980

In [200]:
AAPL.groupby('year')['Open'].mean()

year
1980      0.544299
1981      0.435472
1982      0.341782
1983      0.669096
1984      0.479822
1985      0.370981
1986      0.578346
1987      1.391269
1988      1.484137
1989      1.486253
1990      1.339356
1991      1.873271
1992      1.957273
1993      1.466544
1994      1.216161
1995      1.450822
1996      0.894562
1997      0.644022
1998      1.089720
1999      2.059269
2000      3.270769
2001      1.440377
2002      1.366290
2003      1.322985
2004      2.530105
2005      6.661491
2006     10.141087
2007     18.341298
2008     20.330536
2009     20.945584
2010     37.136803
2011     52.008775
2012     82.378960
2013     67.589734
2014     92.219830
2015    120.175754
2016    104.507778
2017    145.801079
Name: Open, dtype: float64

In [202]:
# 【前提】 必须要用时间作为索引，否则不可以进行重采样操作
temp = AAPL.set_index('Date')

In [205]:
# 分组必聚合
temp.resample('Y')['Open'].mean()

Date
1980-12-31      0.544299
1981-12-31      0.435472
1982-12-31      0.341782
1983-12-31      0.669096
1984-12-31      0.479822
1985-12-31      0.370981
1986-12-31      0.578346
1987-12-31      1.391269
1988-12-31      1.484137
1989-12-31      1.486253
1990-12-31      1.339356
1991-12-31      1.873271
1992-12-31      1.957273
1993-12-31      1.466544
1994-12-31      1.216161
1995-12-31      1.450822
1996-12-31      0.894562
1997-12-31      0.644022
1998-12-31      1.089720
1999-12-31      2.059269
2000-12-31      3.270769
2001-12-31      1.440377
2002-12-31      1.366290
2003-12-31      1.322985
2004-12-31      2.530105
2005-12-31      6.661491
2006-12-31     10.141087
2007-12-31     18.341298
2008-12-31     20.330536
2009-12-31     20.945584
2010-12-31     37.136803
2011-12-31     52.008775
2012-12-31     82.378960
2013-12-31     67.589734
2014-12-31     92.219830
2015-12-31    120.175754
2016-12-31    104.507778
2017-12-31    145.801079
Freq: A-DEC, Name: Open, dtype: float64

In [206]:
# 每3年做一次平均开盘价的计算
temp.resample('3Y')['Open'].mean()

Date
1980-12-31      0.544299
1983-12-31      0.482178
1986-12-31      0.476522
1989-12-31      1.453844
1992-12-31      1.723608
1995-12-31      1.377960
1998-12-31      0.875844
2001-12-31      2.261148
2004-12-31      1.739793
2007-12-31     11.707923
2010-12-31     26.129970
2013-12-31     67.285894
2016-12-31    105.634454
2019-12-31    145.801079
Freq: 3A-DEC, Name: Open, dtype: float64

In [210]:
temp.resample('450D')['Open'].mean()

Date
1980-12-12      0.427127
1982-03-07      0.488095
1983-05-31      0.536549
1984-08-23      0.398354
1985-11-16      0.583333
1987-02-09      1.463742
1988-05-04      1.458290
1989-07-28      1.415980
1990-10-21      1.791388
1992-01-14      1.966183
1993-04-08      1.218321
1994-07-02      1.412297
1995-09-25      0.989845
1996-12-18      0.659303
1998-03-13      1.258129
1999-06-06      3.261042
2000-08-29      1.603286
2001-11-22      1.346151
2003-02-15      1.482952
2004-05-10      4.184655
2005-08-03      9.182532
2006-10-27     17.769439
2008-01-20     18.626375
2009-04-14     27.700827
2010-07-08     46.830269
2011-10-01     77.124722
2012-12-24     69.097638
2014-03-19    106.380942
2015-06-12    107.966977
2016-09-04    136.328602
Freq: 450D, Name: Open, dtype: float64

resample 函数非常灵活，可以指定多种频率转换与重采样参数。

支持聚合函数的处理如： sum、mean、std、sem、max、min、mid、median

## 时间差

Timedelta() 支持用多种参数生成时间差：

unit: Possible values:
    {'Y', 'M', 'W', 'D', 'days', 'day', 'hours', hour', 'hr', 'h',
    'm', 'minute', 'min', 'minutes', 'T', 'S', 'seconds', 'sec', 'second',
    'ms', 'milliseconds', 'millisecond', 'milli', 'millis', 'L',
    'us', 'microseconds', 'microsecond', 'micro', 'micros', 'U',
    'ns', 'nanoseconds', 'nano', 'nanos', 'nanosecond', 'N'}

In [216]:
now = pd.datetime.now()
now

datetime.datetime(2022, 2, 16, 18, 17, 35, 851436)

In [219]:
delta = pd.Timedelta(4, unit='day')
delta

Timedelta('4 days 00:00:00')

In [221]:
future = now + delta

In [222]:
future - now

datetime.timedelta(4)

In [225]:
delta = pd.Timedelta(days=1, seconds=1)

In [226]:
now + delta

datetime.datetime(2022, 2, 17, 18, 17, 36, 851436)

以时间差为数据的 Series 与 DataFrame 支持各种运算，datetime64 [ns] 序列或 Timestamps 减法运算生成的是timedelta64 [ns] 序列。

In [227]:
s = pd.Series(pd.date_range('2012-1-1', periods=3, freq='D'))
td = pd.Series([pd.Timedelta(days=i) for i in range(3)])
df = pd.DataFrame({
    'A':s,
    'B':td
})
df

           A      B
0 2012-01-01 0 days
1 2012-01-02 1 days
2 2012-01-03 2 days

In [229]:
df['C'] = df['A'] + df['B']

In [230]:
df

           A      B          C
0 2012-01-01 0 days 2012-01-01
1 2012-01-02 1 days 2012-01-03
2 2012-01-03 2 days 2012-01-05

In [232]:
s.max()

Timestamp('2012-01-03 00:00:00')

In [233]:
s - s.max()

0   -2 days
1   -1 days
2    0 days
dtype: timedelta64[ns]